name: PublishMSVC
on:   
  push:
    branches:
      - msvc      
  pull_request:
    branches:
      - master
      - develop      
jobs:
  msvc-pack:
    runs-on: windows-latest
    name: Publish MSVC 64
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: oprypin/find-latest-tag@v1
        id: gettag
        with:
          repository: PerryWerneck/vmdetect
          releases-only: true
      - uses: ilammy/msvc-dev-cmd@v1.4.1
      - name: pack
        run: |
          nmake /f win\Makefile.msc
          7z a msvc-vmdetect.zip .\bin\* .\lib\* .\src\include\vmdetect
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.gettag.outputs.tag }}
          artifacts: "*vmdetect*.zip"
          allowUpdates: true
          draft: false
          makeLatest: true
          omitBody: true
          omitPrereleaseDuringUpdate: true
          replacesArtifacts: true

