name: check-msys2
on:
  push:
    branches: [ "win" ]
  pull_request:
    branches: [ "master" ]

jobs:
  msys2-build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: dos2unix xz mingw-w64-x86_64-gcc pkgconf mingw-w64-x86_64-gettext mingw-w64-x86_64-meson gettext-devel
      # Update references
      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
      - name: CI-Build
        run: |
          dos2unix PKGBUILD.mingw
          makepkg BUILDDIR=/tmp/pkg -p PKGBUILD.mingw
