---
name: PyPi
on:
  push:
    branches:
      - python
      - develop
    tags:
      - '*'
jobs:
  python:
    runs-on: ubuntu-latest
    name: Publish Pypi package
    environment:
      name: pytest
      url: https://test.pypi.org/p/virtualmachine
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing  
    steps:
      - uses: actions/checkout@v3
      - name: Build installer
        run: python setup.py sdist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

