---
name: PyPi
on:
  push:
    branches: [ "python" ]
    tags: [ "*" ]

jobs:
  python:
    runs-on: ubuntu-latest
    name: Publish Python package
    environment:
      name: pypi
      url: https://pypi.org/p/virtualmachine
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing  
    steps:
      - uses: actions/checkout@v3
      - name: Build installer
        run: python setup.py sdist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

