name: wincheck
on:
  push:
    branches: [ "win" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check-msys64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup MSys
        uses: msys2/setup-msys2@v2
        with:
          msystem: mingw64
          update: true
          install: git dos2unix xz mingw-w64-x86_64-gcc pkgconf mingw-w64-x86_64-gettext mingw-w64-x86_64-meson gettext-devel
      - name: Build MSys Package
        run: |
          dos2unix PKGBUILD.mingw
          makepkg BUILDDIR=/tmp/pkg -p PKGBUILD.mingw

  check-msvc:
    # https://dvdhrm.github.io/2021/04/21/meson-msvc-github-actions/
    runs-on: windows-latest
    steps:
      - name: Fetch Sources
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Python Dependencies
        run: pip install meson ninja
      - name: Prepare MSVC
        uses: bus1/cabuild/action/msdevshell@v1
        with:
          architecture: x64
      - name: Prepare Build
        run: meson setup build
      - name: Run Build
        run: meson compile -v -C build vmdetect:static_library vmdetect:executable
        